In [362]:
import pandas as pd
import numpy as np

from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.ensemble import RandomForestRegressor

In [363]:
df = pd.read_csv("campusvolt_energy_data.csv")

In [364]:
df.head()

,timestamp,meterId,buildingId,buildingName,voltage,current,power,energy,frequency,powerFactor,temperature,occupancyLevel,weatherCondition,dayType,workingHours,scenario,status,simulationTime,simulationSpeed
0,2025-01-01 00:00:00,M001,B001,Academic Block,232.30,53.68,19.37,19.37,49.962,0.891,19.82,6.59,Sunny,Weekday,False,Normal,Normal,2025-01-01 00:00:00,1
1,2025-01-01 01:00:00,M001,B001,Academic Block,226.96,44.72,15.56,34.93,50.025,0.866,20.73,0.00,Sunny,Weekday,False,Normal,Normal,2025-01-01 01:00:00,1
2,2025-01-01 02:00:00,M001,B001,Academic Block,230.33,33.41,11.96,46.89,49.908,0.889,20.94,7.99,Sunny,Weekday,False,Normal,Normal,2025-01-01 02:00:00,1
3,2025-01-01 03:00:00,M001,B001,Academic Block,232.47,31.70,11.61,58.50,49.902,0.883,19.98,0.00,Cloudy,Weekday,False,Normal,Normal,2025-01-01 03:00:00,1
4,2025-01-01 04:00:00,M001,B001,Academic Block,229.10,38.65,13.48,71.98,49.882,0.873,21.42,9.41,Cloudy,Weekday,False,Normal,Normal,2025-01-01 04:00:00,1

In [365]:
print(df.shape)

(43800, 19)

In [366]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 43800 entries, 0 to 43799
Data columns (total 19 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   timestamp         43800 non-null  str
 1   meterId           43800 non-null  str
 2   buildingId        43800 non-null  str
 3   buildingName      43800 non-null  str
 4   voltage           43800 non-null  float64
 5   current           43800 non-null  float64
 6   power             43800 non-null  float64
 7   energy            43800 non-null  float64
 8   frequency         43800 non-null  float64
 9   powerFactor       43800 non-null  float64
 10  temperature       43800 non-null  float64
 11  occupancyLevel    43800 non-null  float64
 12  weatherCondition  43800 non-null  str
 13  dayType           43800 non-null  str
 14  workingHours      43800 non-null  bool
 15  scenario          43800 non-null  str
 16  status            43800 non-null  str
 17  simulationTime    43800 non-null  str
 18  simulationSpeed   43800 non-null  int64
dtypes: bool(1), float64(8), int64(1), str(9)
memory usage: 6.1 MB

In [367]:
df.isnull().sum()

timestamp           0
meterId             0
buildingId          0
buildingName        0
voltage             0
current             0
power               0
energy              0
frequency           0
powerFactor         0
temperature         0
occupancyLevel      0
weatherCondition    0
dayType             0
workingHours        0
scenario            0
status              0
simulationTime      0
simulationSpeed     0
dtype: int64

In [368]:
df.describe()

,voltage,current,power,energy,frequency,powerFactor,temperature,occupancyLevel,simulationSpeed
count,43800.000000,43800.000000,43800.000000,43800.000000,43800.000000,43800.000000,43800.000000,43800.000000,43800.0
mean,230.016157,125.717601,44.689157,198519.377843,49.999974,0.887742,30.451116,29.890713,1.0
std,3.001855,91.497930,32.844700,134845.936081,0.079923,0.019233,6.070816,28.796576,0.0
min,217.760000,13.120000,5.000000,5.680000,49.696000,0.813000,13.110000,0.000000,1.0
25%,227.990000,54.500000,19.140000,80004.067500,49.946000,0.874000,25.860000,5.570000,1.0
50%,230.030000,99.230000,34.660000,189833.425000,50.000000,0.887000,30.460000,15.290000,1.0
75%,232.020000,177.090000,63.510000,286277.195000,50.054000,0.900000,35.080000,56.090000,1.0
max,241.830000,665.480000,234.460000,512660.460000,50.376000,0.967000,46.670000,100.000000,1.0

In [369]:
df["timestamp"] = pd.to_datetime(df["timestamp"])
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 43800 entries, 0 to 43799
Data columns (total 19 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   timestamp         43800 non-null  datetime64[us]
 1   meterId           43800 non-null  str
 2   buildingId        43800 non-null  str
 3   buildingName      43800 non-null  str
 4   voltage           43800 non-null  float64
 5   current           43800 non-null  float64
 6   power             43800 non-null  float64
 7   energy            43800 non-null  float64
 8   frequency         43800 non-null  float64
 9   powerFactor       43800 non-null  float64
 10  temperature       43800 non-null  float64
 11  occupancyLevel    43800 non-null  float64
 12  weatherCondition  43800 non-null  str
 13  dayType           43800 non-null  str
 14  workingHours      43800 non-null  bool
 15  scenario          43800 non-null  str
 16  status            43800 non-null  str
 17  simulationTime    43800 non-null  str
 18  simulationSpeed   43800 non-null  int64
dtypes: bool(1), datetime64[us](1), float64(8), int64(1), str(8)
memory usage: 6.1 MB

In [370]:
df["hour"] = df["timestamp"].dt.hour
df["day"] = df["timestamp"].dt.day
df["dayOfWeek"] = df["timestamp"].dt.dayofweek
df["month"] = df["timestamp"].dt.month

In [371]:
df[["timestamp", "hour", "day", "dayOfWeek", "month"]].head()

            timestamp  hour  day  dayOfWeek  month
0 2025-01-01 00:00:00     0    1          2      1
1 2025-01-01 01:00:00     1    1          2      1
2 2025-01-01 02:00:00     2    1          2      1
3 2025-01-01 03:00:00     3    1          2      1
4 2025-01-01 04:00:00     4    1          2      1

In [372]:
df["powerLag1"] = df.groupby("meterId")["power"].shift(1)

In [373]:
df["powerLag24"] = df.groupby("meterId")["power"].shift(24)

In [374]:
df = df.dropna()
df.shape

(43680, 25)

In [375]:
features = [
   "hour",
    "day",
    "dayOfWeek",
    "month",
    "powerLag1",
    "powerLag24",
    "temperature",
    "occupancyLevel"
]

In [376]:
target = "power"

In [377]:
X = df[features]
y = df[target]

In [378]:
df = df.sort_values(["meterId", "timestamp"]).reset_index(drop=True)

In [379]:
df.head()

,timestamp,meterId,buildingId,buildingName,voltage,current,power,energy,frequency,powerFactor,...,scenario,status,simulationTime,simulationSpeed,hour,day,dayOfWeek,month,powerLag1,powerLag24
0,2025-01-02 00:00:00,M001,B001,Academic Block,232.28,40.09,14.30,1120.27,49.938,0.880,...,Normal,Normal,2025-01-02 00:00:00,1,0,2,3,1,18.55,19.37
1,2025-01-02 01:00:00,M001,B001,Academic Block,228.58,38.87,13.78,1134.05,50.087,0.881,...,Normal,Normal,2025-01-02 01:00:00,1,1,2,3,1,14.30,15.56
2,2025-01-02 02:00:00,M001,B001,Academic Block,228.05,34.20,12.39,1146.44,50.172,0.890,...,Normal,Normal,2025-01-02 02:00:00,1,2,2,3,1,13.78,11.96
3,2025-01-02 03:00:00,M001,B001,Academic Block,231.51,21.71,7.55,1153.99,50.069,0.863,...,Normal,Normal,2025-01-02 03:00:00,1,3,2,3,1,12.39,11.61
4,2025-01-02 04:00:00,M001,B001,Academic Block,232.75,22.93,8.47,1162.46,50.170,0.895,...,Normal,Normal,2025-01-02 04:00:00,1,4,2,3,1,7.55,13.48

In [380]:
splitIndex = int(len(df) * 0.8)

XTrain = X.iloc[:splitIndex]
XTest = X.iloc[splitIndex:]

yTrain = y.iloc[:splitIndex]
yTest = y.iloc[splitIndex:]

In [381]:
model = LinearRegression()

In [382]:
model.fit(XTrain, yTrain)

LinearRegression()

In [383]:
yPred = model.predict(XTest)

In [384]:
yTest

35064    12.88
35065    11.11
35066     5.32
35067     5.00
35068     5.00
         ...
43795    14.64
43796    17.62
43797     7.02
43798    12.33
43799    13.77
Name: power, Length: 8736, dtype: float64

In [385]:
mae = mean_absolute_error(yTest, yPred)
rmse = np.sqrt(mean_squared_error(yTest, yPred))
r2 = r2_score(yTest, yPred)

print("MAE:", mae)
print("RMSE:", rmse)
print("R² Score:", r2)

MAE: 5.341297973627237
RMSE: 7.098351497943229
R² Score: 0.9166388893742325

In [386]:
model = RandomForestRegressor()

In [387]:
model = RandomForestRegressor(
    n_estimators=100,
    random_state=42,
    max_depth=20,
    min_samples_split=10
)

In [388]:
model.fit(XTrain,yTrain)

RandomForestRegressor(max_depth=20, min_samples_split=10, random_state=42)

In [389]:
ypredict = model.predict(XTest)

In [390]:
mae = mean_absolute_error(yTest, ypredict)
rmse = np.sqrt(mean_squared_error(yTest, ypredict))
r2 = r2_score(yTest, ypredict)

print("MAE:", mae)
print("RMSE:", rmse)
print("R² Score:", r2)

MAE: 4.713402378029932
RMSE: 7.041076716765606
R² Score: 0.9179787011051462

In [391]:
yPredict = model.predict(XTrain)

In [392]:
mae = mean_absolute_error(yTrain, yPredict)
rmse = np.sqrt(mean_squared_error(yTrain, yPredict))
r2 = r2_score(yTrain, yPredict)

print("MAE:", mae)
print("RMSE:", rmse)
print("R² Score:", r2)

MAE: 2.2075538850545855
RMSE: 3.386510791729202
R² Score: 0.9900868265538283